# Generated by Django 4.1.7 on 2023-03-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Hm',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='Н/м'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Hp',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='Л.с.'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='acceleration',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='Ускорение'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='brake',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='Торможение'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='center',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='Фронтальная нагрузка'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='control',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='kW',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='кВт'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='speed',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='start',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='Разгон'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, default=11, verbose_name='Вес'),
        ),
    ]
