# Generated by Django 4.1.7 on 2023-03-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand',
            field=models.CharField(max_length=150, verbose_name='Бренд'),
        ),
    ]
