# Generated by Django 4.1.7 on 2023-03-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_brands_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Бренд'),
        ),
    ]
