# Generated by Django 4.1.7 on 2023-03-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_brands_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Год'),
        ),
    ]
