# Generated by Django 4.1.7 on 2023-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_cars_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Уровень'),
        ),
    ]
