# Generated by Django 4.1.7 on 2023-03-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_alter_cars_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Уровень'),
        ),
    ]
