# Generated by Django 4.1.7 on 2023-03-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_alter_cars_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
